#!/usr/bin/env bash
# Clone các repo mã nguồn mở đã nghiên cứu để làm kit vào <kit>/_repos/ (không lưu trong git). Xem THIRD-PARTY.md. Commit = bản đã đọc 30/09–05/10/2026.
cd "$(dirname "$0")/.."; mkdir -p _repos/hooks
[ -d _repos/awesome-claude-video-skills ] || git -c core.longpaths=true clone -q https://github.com/zhuyansen/awesome-claude-video-skills.git _repos/awesome-claude-video-skills && git -C _repos/awesome-claude-video-skills -c advice.detachedHead=false checkout -q b116824 2>/dev/null || true; echo "✅ _repos/awesome-claude-video-skills"
[ -d _repos/Claude-Code-Video-Toolkit ] || git -c core.longpaths=true clone -q https://github.com/wilwaldon/Claude-Code-Video-Toolkit.git _repos/Claude-Code-Video-Toolkit && git -C _repos/Claude-Code-Video-Toolkit -c advice.detachedHead=false checkout -q a6e9e52 2>/dev/null || true; echo "✅ _repos/Claude-Code-Video-Toolkit"
[ -d _repos/hyperframes ] || git -c core.longpaths=true clone -q https://github.com/heygen-com/hyperframes.git _repos/hyperframes && git -C _repos/hyperframes -c advice.detachedHead=false checkout -q 9a27b9f 2>/dev/null || true; echo "✅ _repos/hyperframes"
[ -d _repos/hypit ] || git -c core.longpaths=true clone -q https://github.com/hypit-ai/hypit.git _repos/hypit && git -C _repos/hypit -c advice.detachedHead=false checkout -q 7f730ab 2>/dev/null || true; echo "✅ _repos/hypit"
[ -d _repos/OpenMontage ] || git -c core.longpaths=true clone -q https://github.com/calesthio/OpenMontage.git _repos/OpenMontage && git -C _repos/OpenMontage -c advice.detachedHead=false checkout -q 08e2151 2>/dev/null || true; echo "✅ _repos/OpenMontage"
[ -d _repos/soundcn ] || git -c core.longpaths=true clone -q https://github.com/kapishdima/soundcn.git _repos/soundcn && git -C _repos/soundcn -c advice.detachedHead=false checkout -q 7cbfbb3 2>/dev/null || true; echo "✅ _repos/soundcn"
[ -d _repos/uisfx ] || git -c core.longpaths=true clone -q https://github.com/899ms/uisfx.git _repos/uisfx && git -C _repos/uisfx -c advice.detachedHead=false checkout -q 9950fe6 2>/dev/null || true; echo "✅ _repos/uisfx"
[ -d _repos/video-shotcraft ] || git -c core.longpaths=true clone -q https://github.com/Vincentwei1021/video-shotcraft.git _repos/video-shotcraft && git -C _repos/video-shotcraft -c advice.detachedHead=false checkout -q 5ddbf52 2>/dev/null || true; echo "✅ _repos/video-shotcraft"
[ -d _repos/hooks/hooksmith ] || git -c core.longpaths=true clone -q https://github.com/arhamhi/hooksmith.git _repos/hooks/hooksmith && git -C _repos/hooks/hooksmith -c advice.detachedHead=false checkout -q 1a1c13c 2>/dev/null || true; echo "✅ _repos/hooks/hooksmith"
[ -d _repos/hooks/short-form-video-scripts ] || git -c core.longpaths=true clone -q https://github.com/jakeolschewski/short-form-video-scripts.git _repos/hooks/short-form-video-scripts && git -C _repos/hooks/short-form-video-scripts -c advice.detachedHead=false checkout -q f4f83d2 2>/dev/null || true; echo "✅ _repos/hooks/short-form-video-scripts"
[ -d _repos/hooks/tiktok-viral-hooks ] || git -c core.longpaths=true clone -q https://github.com/shixinzhang/tiktok-viral-hooks.git _repos/hooks/tiktok-viral-hooks && git -C _repos/hooks/tiktok-viral-hooks -c advice.detachedHead=false checkout -q eaae981 2>/dev/null || true; echo "✅ _repos/hooks/tiktok-viral-hooks"
[ -d _repos/hooks/viral-video-decomposer ] || git -c core.longpaths=true clone -q https://github.com/sharon-laicc/viral-video-decomposer.git _repos/hooks/viral-video-decomposer && git -C _repos/hooks/viral-video-decomposer -c advice.detachedHead=false checkout -q 3409359 2>/dev/null || true; echo "✅ _repos/hooks/viral-video-decomposer"
